FROM python:3.9 as requirements-stage
WORKDIR /tmp
RUN pip install poetry
COPY ./pyproject.toml ./poetry.lock* /tmp/
RUN poetry export -f requirements.txt --output requirements.txt --without-hashes

FROM tiangolo/uvicorn-gunicorn:python3.11
COPY --from=requirements-stage /tmp/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt
COPY ./fa_rss /app/fa_rss
COPY ./templates /app/templates
COPY ./pyproject.toml /app/pyproject.toml
WORKDIR /app
EXPOSE 80
ENV MODULE_NAME "fa_rss.app"
ENV VARIABLE_NAME "app_dispatch"
